services:
  backend:
    build: 
      context: ./blog_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./blog_backend/.env
    command: >
      sh -c "./wait-for-it.sh db:5432 -- 
      && . .venv/bin/activate 
      && python manage.py migrate 
      && python manage.py collectstatic --noinput 
      && python manage.py createsuperuser --no-input || true 
      && uvicorn blog_backend.asgi:application --host 0.0.0.0 --port 8000 --workers 4"

    volumes:
      - ./blog_backend:/app

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./blog_backend/.env
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./blog_frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    env_file:
      - ./blog_frontend/.env
    command: >
      sh -c "pnpm install && ng serve --host 0.0.0.0"
    volumes:
      - ./blog_frontend:/app

volumes:
  db_data:
